cache_dir: ./cache
output_dir: ./output

timeout: 450
interval: 600

host: 0.0.0.0
port: 8888

rpki_client: /usr/bin/rpki-client

trust_anchor_locators:
  - /etc/pki/tals/ripe.tal
    #  - /etc/pki/tals/afrinic.tal
